<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'SikTec\\Exceptions\\InvalidArgumentException' => $baseDir . '/src/templating/exceptions/InvalidArgumentException.php',
    'SikTec\\Exceptions\\RuntimeException' => $baseDir . '/src/templating/exceptions/RuntimeException.php',
    'SikTec\\SikTemplates\\Exception' => $baseDir . '/src/templating/exceptions/Exception.php',
    'SikTec\\SikTemplates\\Template' => $baseDir . '/src/templating/SikTemplate.class.php',
    'TidePlugin\\Inputs\\InputField' => $baseDir . '/src/Inputs/InputField.php',
    'TidePlugin\\Inputs\\NumberField' => $baseDir . '/src/Inputs/NumberField.php',
    'TidePlugin\\Inputs\\SelectField' => $baseDir . '/src/Inputs/SelectField.php',
    'TidePlugin\\Inputs\\TextAreaField' => $baseDir . '/src/Inputs/TextAreaField.php',
    'TidePlugin\\Inputs\\TextField' => $baseDir . '/src/Inputs/TextField.php',
    'TidePlugin\\Inputs\\ToggleField' => $baseDir . '/src/Inputs/ToggleField.php',
    'TidePlugin\\MainPlugin' => $baseDir . '/src/MainPlugin.class.php',
    'TidePlugin\\ShortCode' => $baseDir . '/src/TideShortcode.class.php',
    'TidePlugin\\Tide' => $baseDir . '/src/Tide.class.php',
    'TidePlugin\\Widgets\\TideTableWidget' => $baseDir . '/src/Widgets.class.php',
);
